# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Pnt_Con
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Pnt_Con_Ple
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Ple
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Emp_Ple
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Ede_Emp_Ple
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Ede_Emp_Fib_Ple
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
python -W ignore supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor

# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Pnt_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Mas_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her
# python -W ignore supervised_experiments/train_nih_profiling.py --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor

# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Pnt_Con_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Pnt_Con_Ple_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Ple_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Emp_Ple_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Ede_Emp_Ple_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pnt_Con_Ede_Emp_Fib_Ple_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor

# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Pnt_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Mas_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor