# Ate_Car_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ede_Emp_Fib_Ple_Her_Nor
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Inf
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Nod
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Con

python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Her
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Fib_Her
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Ede_Fib_Her
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Ede_Emp_Fib_Her
python -W ignore supervised_experiments/train_nih_profiling.py  --label nih --optimizer baseline --dataset nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Ede_Emp_Fib_Her

python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Pne_Pnt_Con_Ple_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Pne_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Eff_Pne_Nor_Cov

python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Inf_Pne_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Mas_Pne_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Nod_Pne_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Pnt_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Con_Nor_Cov
python -W ignore supervised_experiments/train_cov_nih_partial.py  --label cov_nih --optimizer baseline --dataset cov_nih --batch_size 16 --lr 0.001 --decay_lr --num_epochs 20 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Ple_Nor_Cov

# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Inf_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Inf_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Nod_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Ate_Eff_Inf_Mas_Nod_Con_Nor


# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Fib_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Ede_Fib_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Pne_Ede_Emp_Fib_Her_Nor
# python supervised_experiments/train_nih_partial.py --label nih --optimizer baseline --dataset nih --batch_size 8 --lr 0.001 --decay_lr --num_epochs 50 --store_models  --random_seed 1 --n_runs 2 --partial_dataset True --nih_labels Car_Pne_Ede_Emp_Fib_Her_Nor
